In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as okt
import seaborn as sns
sns.set()
from scipy import optimize
from ipywidgets import *
from IPython.display import SVG
from sklearn import datasets

In [56]:
AND = pd.DataFrame({'x1':(0,0,1,1),'x2':(0,1,0,1),'y':(0,0,0,1)})
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

#### First, we need to initialize weights to small, random values ( positive and negative).

In [57]:
w = np.random.rand(3)*1e-4

In [58]:
w

array([3.90624255e-05, 6.63210479e-06, 6.74000967e-05])

####Then, a simple activation function for calculating *g(h):*

In [39]:
g = lambda inputs, weights:np.where(np.dot(inputs,weights)>0,1,0)

#### Finally, a training function that iterates the learning algorithm, returning the adapted weights.

In [52]:
def train(inputs, targets, weights, eta, n_iterations):
  # Add inputs that match the bias node
  inputs = np.c_[inputs,-np.ones((len(inputs),1))]
  for i in range(n_iterations):
      activation = g(inputs,weights);
      # print(i, activation)
      weights -= eta*np.dot(np.transpose(inputs), activation - targets)
      # print(i, weights)

  return weights


#### Let's test it on the AND function.

In [53]:
inputs = AND[['x1','x2']]
target = AND['y']
w = train(inputs,target,w,10,10)

# target

0 [0 0 0 1]
0 [1.00000052e+01 9.98122418e-05 1.00000201e+01]
1 [0 0 0 1]
1 [1.00000052e+01 9.98122418e-05 1.00000201e+01]
2 [0 0 0 1]
2 [1.00000052e+01 9.98122418e-05 1.00000201e+01]
3 [0 0 0 1]
3 [1.00000052e+01 9.98122418e-05 1.00000201e+01]
4 [0 0 0 1]
4 [1.00000052e+01 9.98122418e-05 1.00000201e+01]
5 [0 0 0 1]
5 [1.00000052e+01 9.98122418e-05 1.00000201e+01]
6 [0 0 0 1]
6 [1.00000052e+01 9.98122418e-05 1.00000201e+01]
7 [0 0 0 1]
7 [1.00000052e+01 9.98122418e-05 1.00000201e+01]
8 [0 0 0 1]
8 [1.00000052e+01 9.98122418e-05 1.00000201e+01]
9 [0 0 0 1]
9 [1.00000052e+01 9.98122418e-05 1.00000201e+01]


0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [54]:
w

array([1.00000052e+01, 9.98122418e-05, 1.00000201e+01])

In [48]:
g(np.c_[inputs,-np.ones((len(inputs),1))],w)

array([0, 0, 0, 1])